// type
// 0 实际值*倍数
// 1 变频9 工频17 休息2 热继故障36 空开跳闸68 变频故障132
// 2 无水故障 1 高水信号2 地面积水信号4 相序故障8 出口超压16 门禁报警32
// 3 自动0 手动1
// 4 开启1 关闭0
// 5 是1 否0
export default [
{
name: "二次供水 MODBUS PLC点表",
pointEnum:
[{
    number: 1,
    name: "泵前压力",
    place:0,
    placeLength:0,
    type: 0,
    times: 1000,
    unit: "Mpa",
    floatNum: 0,
    isWrite:0,
},
{
    number: 2,
    name: "泵后压力",
    place:0,
    placeLength:0,
    type: 0,
    times: 1000,
    unit: "Mpa",
    floatNum: 0,
    isWrite:0,
},
{
    number: 3,
    name: "1#泵状态",
    place:0,
    placeLength:0,
    type: 1,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 4,
    name: "2#泵状态",
    place:0,
    placeLength:0,
    type: 1,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 5,
    name: "3#泵状态",
    place:0,
    placeLength:0,
    type: 1,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 6,
    name: "4#泵状态",
    place:0,
    placeLength:0,
    type: 1,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 7,
    name: "5#泵状态",
    place:0,
    placeLength:0,
    type: 1,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 8,
    name: "6#泵状态",
    place:0,
    placeLength:0,
    type: 1,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 9,
    name: "7#泵状态",
    place:0,
    placeLength:0,
    type: 1,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 10,
    name: "8#泵状态",
    place:0,
    placeLength:0,
    type: 1,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 11,
    name: "其他信号故障",
    place:0,
    placeLength:0,
    type: 2,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 12,
    name: "电机电流Ia",
    place:0,
    placeLength:0,
    type: 0,
    times: 10,
    unit: "An",
    floatNum: 0,
    isWrite:0,
},
{
    number: 13,
    name: "电机电流Ib",
    place:0,
    placeLength:0,
    type: 0,
    times: 10,
    unit: "An",
    floatNum: 0,
    isWrite:0,
},
{
    number: 14,
    name: "电机电流Ic",
    place:0,
    placeLength:0,
    type: 0,
    times: 10,
    unit: "An",
    floatNum: 0,
    isWrite:0,
},
{
    number: 15,
    name: "电机电压Ua",
    place:0,
    placeLength:0,
    type: 0,
    times: 10,
    unit: "V",
    floatNum: 0,
    isWrite:0,
},
{
    number: 16,
    name: "电机电压Ub",
    place:0,
    placeLength:0,
    type: 0,
    times: 10,
    unit: "V",
    floatNum: 0,
    isWrite:0,
},
{
    number: 17,
    name: "电机电压Uc",
    place:0,
    placeLength:0,
    type: 0,
    times: 10,
    unit: "V",
    floatNum: 0,
    isWrite:0,
},
{
    number: 18,
    name: "1#变频器频率",
    place:0,
    placeLength:0,
    type: 0,
    times: 100,
    unit: "Hz",
    floatNum: 0,
    isWrite:0,
},
{
    number: 19,
    name: "1#变频器频率",
    place:0,
    placeLength:0,
    type: 0,
    times: 100,
    unit: "Hz",
    floatNum: 0,
    isWrite:0,
},
{
    number: 20,
    name: "3#变频器频率",
    place:0,
    placeLength:0,
    type: 0,
    times: 100,
    unit: "Hz",
    floatNum: 0,
    isWrite:0,
},
{
    number: 21,
    name: "4#变频器频率",
    place:0,
    placeLength:0,
    type: 0,
    times: 100,
    unit: "Hz",
    floatNum: 0,
    isWrite:0,
},
{
    number: 22,
    name: "5#变频器频率",
    place:0,
    placeLength:0,
    type: 0,
    times: 100,
    unit: "Hz",
    floatNum: 0,
    isWrite:0,
},
{
    number: 23,
    name: "6#变频器频率",
    place:0,
    placeLength:0,
    type: 0,
    times: 100,
    unit: "Hz",
    floatNum: 0,
    isWrite:0,
},
{
    number: 24,
    name: "7#变频器频率",
    place:0,
    placeLength:0,
    type: 0,
    times: 100,
    unit: "Hz",
    floatNum: 0,
    isWrite:0,
},
{
    number: 25,
    name: "8#变频器频率",
    place:0,
    placeLength:0,
    type: 0,
    times: 100,
    unit: "Hz",
    floatNum: 0,
    isWrite:0,
},
{
    number: 26,
    name: "水箱水位",
    place:0,
    placeLength:0,
    type: 0,
    times: 100,
    unit: "cm",
    floatNum: 0,
    isWrite:0,
},
{
    number: 27,
    name: "出口流量",
    place:0,
    placeLength:0,
    type: 0,
    times: 10,
    unit: "t/h",
    floatNum: 0,
    isWrite:0,
},
{
    number: 28,
    name: "累计流量低位",
    place:0,
    placeLength:0,
    type: 0,
    times: 1,
    unit: "t/h",
    floatNum: 0,
    isWrite:0,
},
{
    number: 29,
    name: "累计流量高位",
    place:0,
    placeLength:0,
    type: 0,
    times: 1,
    unit: "t/h",
    floatNum: 0,
    isWrite:0,
},
{
    number: 30,
    name: "累计电量低位",
    place:0,
    placeLength:0,
    type: 0,
    times: 1,
    unit: "An",
    floatNum: 0,
    isWrite:0,
},
{
    number: 31,
    name: "累计电量高位",
    place:0,
    placeLength:0,
    type: 0,
    times: 1,
    unit: "An",
    floatNum: 0,
    isWrite:0,
},
{
    number: 32,
    name: "远程切换自动/手动",
    place:0,
    placeLength:0,
    type: 3,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 33,
    name: "远程启停水泵1#",
    place:0,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 34,
    name: "远程启停水泵2#",
    place:0,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 35,
    name: "远程启停水泵3#",
    place:0,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 36,
    name: "远程启停水泵4#",
    place:0,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 37,
    name: "远程启停水泵5#",
    place:0,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 38,
    name: "远程启停水泵6#",
    place:0,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 39,
    name: "远程启停水泵7#",
    place:0,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 40,
    name: "远程启停水泵8#",
    place:0,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 41,
    name: "远程开灯",
    place:0,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
}]
},
{
name: "二次供水 TCP PLC点表",
pointEnum:
[{
    number: 1,
    name: "泵前压力",
    place:1000,
    placeLength:4,
    type: 0,
    times: 1000,
    unit: "Mpa",
    floatNum: 3,
    isWrite:0,
},
{
    number: 2,
    name: "泵后压力",
    place:1004,
    placeLength:4,
    type: 0,
    times: 1000,
    unit: "Mpa",
    floatNum: 3,
    isWrite:0,
},
{
    number: 3,
    name: "水箱水位",
    place:"1008",
    placeLength:4,
    type: 0,
    times: 1,
    unit: "m",
    floatNum: 3,
    isWrite:0,
},
{
    number: 4,
    name: "电机电流Ia",
    place:1012,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "A",
    floatNum: 1,
    isWrite:0,
},
{
    number: 5,
    name: "电机电流Ib",
    place:1016,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "A",
    floatNum: 1,
    isWrite:0,
},
{
    number: 6,
    name: "电机电流Ic",
    place:1020,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "A",
    floatNum: 1,
    isWrite:0,
},
{
    number: 7,
    name: "电机电压Ua",
    place:1024,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "V",
    floatNum: 1,
    isWrite:0,
},
{
    number: 8,
    name: "电机电压Ub",
    place:1028,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "V",
    floatNum: 1,
    isWrite:0,
},
{
    number: 9,
    name: "电机电压Uc",
    place:1032,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "V",
    floatNum: 1,
    isWrite:0,
},
{
    number: 10,
    name: "1#泵变频器频率",
    place:1036,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "Hz",
    floatNum: 2,
    isWrite:0,
},
{
    number: 11,
    name: "2#泵变频器频率",
    place:1040,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "Hz",
    floatNum: 2,
    isWrite:0,
},
{
    number: 12,
    name: "3#泵变频器频率",
    place:1044,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "Hz",
    floatNum: 2,
    isWrite:0,
},
{
    number: 13,
    name: "4#泵变频器频率",
    place:1048,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "Hz",
    floatNum: 2,
    isWrite:0,
},
{
    number: 14,
    name: "5#泵变频器频率",
    place:1052,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "Hz",
    floatNum: 2,
    isWrite:0,
},
{
    number: 15,
    name: "辅泵变频器频率",
    place:1056,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "Hz",
    floatNum: 2,
    isWrite:0,
},
{
    number: 16,
    name: "出水瞬时流量1",
    place:1060,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "M3/h",
    floatNum: 2,
    isWrite:0,
},
{
    number: 17,
    name: "出水累计流量1",
    place:1064,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "M3",
    floatNum: 1,
    isWrite:0,
},
{
    number: 18,
    name: "出水瞬时流量2",
    place:1068,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "M3/h",
    floatNum: 2,
    isWrite:0,
},
{
    number: 19,
    name: "出水累积流量2",
    place:1072,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "M3",
    floatNum: 1,
    isWrite:0,
},
{
    number: 20,
    name: "累积电量",
    place:1076,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "KWH",
    floatNum: 1,
    isWrite:0,
},
{
    number: 21,
    name: "进水电动阀开度",
    place:1080,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "%",
    floatNum: 1,
    isWrite:0,
},
{
    number: 22,
    name: "1#泵变频运行",
    place:1084.0,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 23,
    name: "1#泵休息",
    place:1084.1,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 24,
    name: "1#泵空开跳闸",
    place:1084.2,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 25,
    name: "1#泵变频故障",
    place:1084.3,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 26,
    name: "2#泵变频运行",
    place:1084.4,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 27,
    name: "2#泵休息",
    place:1084.5,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 28,
    name: "2#泵空开跳闸",
    place:1084.6,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 29,
    name: "2#泵变频故障",
    place:1084.7,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
},
{
    number: 30,
    name: "3#泵变频运行",
    place:1085.0,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 31,
    name: "3#泵休息",
    place:1085.1,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 32,
    name: "3#泵空开跳闸",
    place:1085.2,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 33,
    name: "3#泵变频故障",
    place:1085.3,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 34,
    name: "4#泵变频运行",
    place:1085.4,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 35,
    name: "4#泵休息",
    place:1085.5,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 36,
    name: "4#泵空开跳闸",
    place:1085.6,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 37,
    name: "4#泵变频故障",
    place:1085.7,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 38,
    name: "5#泵变频运行",
    place:1086.0,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 39,
    name: "5#泵休息",
    place:1086.1,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 40,
    name: "5#泵空开跳闸",
    place:1086.2,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 41,
    name: "5#泵变频故障",
    place:1086.3,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 42,
    name: "辅泵变频运行",
    place:1086.4,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 43,
    name: "辅泵休息",
    place:1086.5,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 44,
    name: "辅泵空开跳闸",
    place:1086.6,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 45,
    name: "辅泵变频故障",
    place:1086.7,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 46,
    name: "无水故障",
    place:1087.0,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 47,
    name: "高水信号",
    place:1087.1,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 48,
    name: "地面积水信号",
    place:1087.2,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 49,
    name: "相序故障",
    place:1087.3,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 50,
    name: "出口超压",
    place:1087.4,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 51,
    name: "开停机远程控制切换",
    place:1088.0,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 52,
    name: "进水阀远程控制切换",
    place:1088.1,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 53,
    name: "正常开门信号1",
    place:1088.2,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 54,
    name: "非法入侵信号1",
    place:1088.3,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 55,
    name: "正常开门信号2",
    place:1088.4,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 56,
    name: "非法入侵信号2",
    place:1088.5,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 57,
    name: "远程启停1#泵",
    place:1089.0,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 1,
    isWrite:0,
},
{
    number: 58,
    name: "远程启停2#泵",
    place:1089.1,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 59,
    name: "远程启停3#泵",
    place:1089.2,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 60,
    name: "远程启停4#泵",
    place:1089.3,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 61,
    name: "远程启停5#泵",
    place:1089.4,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 62,
    name: "远程启停6#泵",
    place:1089.5,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 63,
    name: "视频监控报警信号",
    place:1089.6,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 64,
    name: "远程进水电动阀调节",
    place:1090,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
}]
},
{
    name: "污水 TCP PLC点表",
    pointEnum:
    [{
        number: 1,
        name: "1#风机手/自动",
        place:2000.0,
        placeLength:0,
        type: 3,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 2,
        name: "1#风机启动命令",
        place:2000.1,
        placeLength:0,
        type: 4,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 3,
        name: "1#风机停止命令",
        place:2000.2,
        placeLength:0,
        type: 4,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 4,
        name: "1#风机故障信号",
        place:2000.3,
        placeLength:0,
        type: 5,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:0,
    },
    {
        number: 5,
        name: "1#风机运行信号",
        place:2000.4,
        placeLength:0,
        type: 5,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:0,
    },
    {
        number: 6,
        name: "2#风机手/自动",
        place:2001.0,
        placeLength:0,
        type: 3,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 7,
        name: "2#风机启动命令",
        place:2001.1,
        placeLength:0,
        type: 4,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 8,
        name: "2#风机停止命令",
        place:2001.2,
        placeLength:0,
        type: 4,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 9,
        name: "2#风机故障信号",
        place:2001.3,
        placeLength:0,
        type: 5,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:0,
    },
    {
        number: 10,
        name: "2#风机运行信号",
        place:2001.4,
        placeLength:0,
        type: 5,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:0,
    },
    {
        number: 11,
        name: "1#提升泵手/自动",
        place:2002.0,
        placeLength:0,
        type: 3,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 12,
        name: "1#提升泵启动命令",
        place:2002.1,
        placeLength:0,
        type: 4,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 13,
        name: "1#提升泵停止命令",
        place:2002.2,
        placeLength:0,
        type: 4,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 14,
        name: "1#提升泵故障信号",
        place:2002.3,
        placeLength:0,
        type: 5,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:0,
    },
    {
        number: 15,
        name: "1#提升泵运行信号",
        place:2002.4,
        placeLength:0,
        type: 5,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:0,
    },
    {
        number: 16,
        name: "2#提升泵手/自动",
        place:2003.0,
        placeLength:0,
        type: 3,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 17,
        name: "2#提升泵启动命令",
        place:2003.1,
        placeLength:0,
        type: 4,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 18,
        name: "2#提升泵停止命令",
        place:2003.2,
        placeLength:0,
        type: 4,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 19,
        name: "2#提升泵故障信号",
        place:2003.3,
        placeLength:0,
        type: 5,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:0,
    },
    {
        number: 20,
        name: "2#提升泵运行信号",
        place:2003.4,
        placeLength:0,
        type: 5,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:0,
    },
    {
        number: 21,
        name: "1#污泥泵手/自动",
        place:2004.0,
        placeLength:0,
        type: 3,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 22,
        name: "1#污泥泵启动命令",
        place:2004.1,
        placeLength:0,
        type: 4,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 23,
        name: "1#污泥泵停止命令",
        place:2004.2,
        placeLength:0,
        type: 4,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 24,
        name: "1#污泥泵故障信号",
        place:2004.3,
        placeLength:0,
        type: 5,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:0,
    },
    {
        number: 25,
        name: "1#污泥泵运行信号",
        place:2004.4,
        placeLength:0,
        type: 5,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:0,
    },
    {
        number: 26,
        name: "2#污泥泵手/自动",
        place:2005.0,
        placeLength:0,
        type: 3,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 27,
        name: "2#污泥泵启动命令",
        place:2005.1,
        placeLength:0,
        type: 4,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 28,
        name: "2#污泥泵停止命令",
        place:2005.2,
        placeLength:0,
        type: 4,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 29,
        name: "2#污泥泵故障信号",
        place:2005.3,
        placeLength:0,
        type: 5,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:0,
    },
    {
        number: 30,
        name: "2#污泥泵运行信号",
        place:2005.4,
        placeLength:0,
        type: 5,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:0,
    },
    {
        number: 31,
        name: "1#回流泵手/自动",
        place:2006.0,
        placeLength:0,
        type: 3,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 32,
        name: "1#回流泵启动命令",
        place:2006.1,
        placeLength:0,
        type: 4,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 33,
        name: "1#回流泵停止命令",
        place:2006.2,
        placeLength:0,
        type: 4,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 34,
        name: "1#回流泵故障信号",
        place:2006.3,
        placeLength:0,
        type: 5,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:0,
    },
    {
        number: 35,
        name: "1#回流泵运行信号",
        place:2006.4,
        placeLength:0,
        type: 5,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:0,
    },
    {
        number: 36,
        name: "2#回流泵手/自动",
        place:2007.0,
        placeLength:0,
        type: 3,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 37,
        name: "2#回流泵启动命令",
        place:2007.1,
        placeLength:0,
        type: 4,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 38,
        name: "2#回流泵停止命令",
        place:2007.2,
        placeLength:0,
        type: 4,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
    {
        number: 39,
        name: "2#回流泵故障信号",
        place:2007.3,
        placeLength:0,
        type: 5,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:0,
    },
    {
        number: 40,
        name: "2#回流泵运行信号",
        place:2007.4,
        placeLength:0,
        type: 5,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:0,
    },
    {
        number: 41,
        name: "1#MBR泵手/自动",
        place:2008.0,
        placeLength:0,
        type: 3,
        times: 1,
        unit: "",
        floatNum: 0,
        isWrite:1,
    },
{
    number: 42,
    name: "1#MBR泵启动命令",
    place:2008.1,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 43,
    name: "1#MBR泵停止命令",
    place:2008.2,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 44,
    name: "1#MBR泵故障信号",
    place:2008.3,
    placeLength:0,
    type: 5,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 45,
    name: "1#MBR泵运行信号",
    place:2008.4,
    placeLength:0,
    type: 5,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 46,
    name: "2#MBR泵手/自动",
    place:2009.0,
    placeLength:0,
    type: 3,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 47,
    name: "2#MBR泵启动命令",
    place:2009.1,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 48,
    name: "2#MBR泵停止命令",
    place:2009.2,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 49,
    name: "2#MBR泵故障信号",
    place:2009.3,
    placeLength:0,
    type: 5,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 50,
    name: "2#MBR泵运行信号",
    place:2009.4,
    placeLength:0,
    type: 5,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 51,
    name: "1#反洗泵手/自动",
    place:2010.0,
    placeLength:0,
    type: 3,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 52,
    name: "1#反洗泵启动命令",
    place:2010.1,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 53,
    name: "1#反洗泵停止命令",
    place:2010.2,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 54,
    name: "1#反洗泵故障信号",
    place:2010.3,
    placeLength:0,
    type: 5,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 55,
    name: "1#反洗泵运行信号",
    place:2010.4,
    placeLength:0,
    type: 5,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 56,
    name: "2#反洗泵手/自动",
    place:2011.0,
    placeLength:0,
    type: 3,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 57,
    name: "2#反洗泵启动命令",
    place:2011.1,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 58,
    name: "2#反洗泵停止命令",
    place:2011.2,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 59,
    name: "2#反洗泵故障信号",
    place:2011.3,
    placeLength:0,
    type: 5,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 60,
    name: "2#反洗泵运行信号",
    place:2011.4,
    placeLength:0,
    type: 5,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 61,
    name: "1#化粪池泵手/自动",
    place:2012.0,
    placeLength:0,
    type: 3,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 62,
    name: "1#化粪池泵启动命令",
    place:2012.1,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 63,
    name: "1#化粪池泵停止命令",
    place:2012.2,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 64,
    name: "1#化粪池泵故障信号",
    place:2012.3,
    placeLength:0,
    type: 5,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 65,
    name: "1#化粪池泵运行信号",
    place:2012.4,
    placeLength:0,
    type: 5,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 66,
    name: "2#化粪池泵手/自动",
    place:2013.0,
    placeLength:0,
    type: 3,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 67,
    name: "2#化粪池泵启动命令",
    place:2013.1,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 68,
    name: "2#化粪池泵停止命令",
    place:2013.2,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 69,
    name: "2#化粪池泵故障信号",
    place:2013.3,
    placeLength:0,
    type: 5,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 70,
    name: "2#化粪池泵运行信号",
    place:2013.4,
    placeLength:0,
    type: 5,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 71,
    name: "格栅机手/自动",
    place:2014.0,
    placeLength:0,
    type: 3,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 72,
    name: "格栅机启动命令",
    place:2014.1,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 73,
    name: "格栅机停止命令",
    place:2014.2,
    placeLength:0,
    type: 4,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 74,
    name: "格栅机故障信号",
    place:2014.3,
    placeLength:0,
    type: 5,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 75,
    name: "格栅机运行信号",
    place:2014.4,
    placeLength:0,
    type: 5,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 76,
    name: "调节池低液位报警",
    place:2017.0,
    placeLength:0,
    type: 5,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 77,
    name: "调节池高液位报警",
    place:2017.1,
    placeLength:0,
    type: 5,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:0,
},
{
    number: 78,
    name: "风机运行时间设定",
    place:2030,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 79,
    name: "风机休息时间设定",
    place:2032,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 80,
    name: "风机轮换时间设定",
    place:2034,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 81,
    name: "提升泵轮换时间设定",
    place:2036,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 82,
    name: "污泥泵运行时间设定",
    place:2038,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 83,
    name: "污泥泵休息时间设定",
    place:2040,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 84,
    name: "污泥泵轮换时间设定",
    place:2042,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 85,
    name: "回流泵运行时间设定",
    place:2044,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 86,
    name: "回流泵休息时间设定",
    place:2046,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 87,
    name: "回流泵轮换时间设定",
    place:2048,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 88,
    name: "MBR泵运行时间设定",
    place:2050,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 89,
    name: "MBR泵休息时间设定",
    place:2052,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 90,
    name: "MBR泵轮换时间设定",
    place:2054,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 91,
    name: "反洗泵运行时间设定",
    place:2056,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 92,
    name: "反洗泵休息时间设定",
    place:2058,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 93,
    name: "反洗泵轮换时间设定",
    place:2060,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 94,
    name: "化粪池泵运行时间设定",
    place:2062,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 95,
    name: "化粪池泵休息时间设定",
    place:2064,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 96,
    name: "化粪池泵轮换时间设定",
    place:2068,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 97,
    name: "格栅机运行时间设定",
    place:2070,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 98,
    name: "格栅机休息时间设定",
    place:2072,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "min",
    floatNum: 0,
    isWrite:1,
},
{
    number: 99,
    name: "氨氮量程设定",
    place:2080,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 100,
    name: "氨氮实时检测",
    place:2082,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 101,
    name: "COD量程设定",
    place:2084,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 102,
    name: "COD实时检测",
    place:2086,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 103,
    name: "PH实时检测",
    place:2088,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "",
    floatNum: 0,
    isWrite:1,
},
{
    number: 104,
    name: "液位量程设定",
    place:2090,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "mm",
    floatNum: 0,
    isWrite:1,
},
{
    number: 105,
    name: "液位反馈",
    place:2092,
    placeLength:2,
    type: 0,
    times: 1,
    unit: "mm",
    floatNum: 0,
    isWrite:1,
},
{
    number: 106,
    name: "累计流量",
    place:2100,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "t",
    floatNum: 0,
    isWrite:1,
},
{
    number: 107,
    name: "瞬时流量",
    place:2104,
    placeLength:4,
    type: 0,
    times: 1,
    unit: "t/h",
    floatNum: 0,
    isWrite:1,
}]
    },
]
